name: mynth_one_client
version: 0.1.0+3
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  chewie: ^1.5.0
  cloud_firestore: ^4.4.3
  cloud_functions: ^4.0.11
  device_preview: ^1.1.0
  dio: ^5.2.1+1
  firebase_auth: ^4.2.9
  firebase_core: ^2.6.1
  firebase_crashlytics: ^3.0.15
  flutter_dotenv: ^5.1.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.0
  flutter_otp_text_field: ^1.1.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  get: 4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.3
  image_cropper: ^4.0.1
  image_picker: ^0.8.9
  jiffy: ^5.0.0
  line_icons: ^2.0.1
  logger: ^1.2.2
  ntp: ^2.0.0
  permission_handler: ^10.3.0
  responsive_framework: ^0.2.0
  smooth_page_indicator: ^1.0.1
  uuid: ^3.0.7
  flutter_launcher_icons: ^0.13.1
  simple_gradient_text: ^1.2.4
  font_awesome_flutter: ^10.4.0
  custom_navigation_bar: ^0.8.2
  animated_text_kit: ^4.2.2
  card_swiper: ^2.0.4
  buttons_tabbar: ^1.3.7+1
  flutter_easyloading: ^3.0.5
  intl: ^0.17.0
  flip_card: ^0.7.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.4.1
  screenshot: ^2.1.0
  share_plus: ^7.1.0
  modal_bottom_sheet: ^2.1.2
  local_auth: ^2.1.7

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env.development
    - .env.staging
    - .env.production
    - assets/icons/app_icon/
    - assets/icons/card_icons/
    - assets/icons/common/
    - assets/icons/isometric/
    - assets/icons/nav_bar/
    - assets/icons/robots/
    - assets/icons/logo/
    - assets/icons/login/
    - assets/images/introduction/
    - assets/images/login/
    - assets/images/otp/
    - assets/mock_data/
